title: Shar K Portfolio
description: Projects and bio
theme: minima
# Show Projects and About in the top nav
header_pages:
  - projects.md
  - about.md
# Optional social links (edit or remove)
minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/YOUR-USERNAME" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN/" }
