title: Sharon Cai's Portfolio
description: A little insight into me and my projects!
theme: minima

# Show Projects and About in the top nav
header_pages:
  - projects.md
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: github,         user_url: "https://github.com/shar-cai" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/cai-s/" }
