title: Sharon Cai's Portfolio
description: A little insight into me and my projects!
theme: minima

# Show Projects and About in the top nav
header_pages:
  - projects.md
  - about.md

minima:
  skin: dark

github_username: shar-cai
linkedin_username: cai-s

.site-footer .footer-col-1 .site-title {
  display: none;
}
